global:
  scrape_interval: 5s

scrape_configs:
  - job_name: operis-project-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ "172.17.0.1:9091" ]
  - job_name: operis-user-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ "172.17.0.1:9092" ]
  - job_name: operis-notification-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ "172.17.0.1:9093" ]
  - job_name: operis-cta-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ "172.17.0.1:9094" ]
  - job_name: operis-task-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ "172.17.0.1:9095" ]
  - job_name: operis-subscription-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ "172.17.0.1:9096" ]
