server:
  port: 0

spring:
  application:
    name: operis-notification-service
  config:
    import: optional:configserver:/
  cloud:
    config:
      discovery:
        enabled: true
        service-id: operis-configuration-server
